Capstone feature
biruk-bereka/software-developer-summit pull request #1
Opened 2023-01-05 19:59 UTC by biruk-bereka

## In this PR I add different feature for conferance page: 

- [ ] Design made using the provided guidelines.
- [ ] Personalize project
- [ ] Use HTML5 , CSS3 and JavaScript
- [ ] The home page has a link in the menu to the about page.
- [ ] The logo in the header links to the home page.
- [ ] When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- [ ] The mobile menu has a close (X) button that closes the menu.
- [ ] The section "Featured speakers" is created dynamically in JavaScript.

## Project Documentation
**Link for Loom Video about the project**
```sh
  https://loom.com/share/1f299105975c4bc28a76c64513f0bcb2
```
**Link for the live version of the project**
```sh
https://biruk-bereka.github.io/software-developer-summit/
```

2023-01-05 21:55 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @biruk-bereka, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 21:55 UTC, anagudelogu commented on README.md
> +This project is only for student purpose, the design is based in the template from [Cindy Shin](https://www.behance.net/adagio07).
- [ ] **[OPTIONAL]:** You did a great job giving the appropriate credits to the author! However, please use the "Acknowledgments" section made for this purpose and that you deleted. 🤓 🛠️

2023-01-05 21:55 UTC, anagudelogu commented on index.html
> +        </div>
- [ ] You did a great job working on the mobile menu of your project! 🥇 However, it would be great if you could fix a bit the styling. At the moment, your menu is pushing the whole content down, causing it to blink a bit whenever you open/close it. This behavior affects tremendously the user experience. Instead, I suggest you use properties like `position: fixed` or `position: absolute` to get your menu out of the normal flow and give the feeling of overlapping the content. 🤓 🛠️ 
![image](https://user-images.githubusercontent.com/77069011/210884049-2043a696-855b-4302-b176-31accdb2bea2.png)

- [ ] **[OPTIONAL]:** If you want to improve further the user experience it would be great if you either prevent the scrolling when the menu is open (This is great if the menu is fullscreen) or stick the menu to the screen, so when it is open, it follows the scrolling. 🤓 🛠️

2023-01-05 21:55 UTC, anagudelogu commented on index.html
> +    </footer>
- [ ] Please consider including the footer on your mobile version! 🤓 🛠️

2023-01-05 21:55 UTC, anagudelogu commented on index.html
> +              src="./assets/images/icons/program_icon_01.png"
- You did a good job working on the main program section! 💯 However, there's still some room to improve the design:

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/210884656-5e9f6d4f-e218-4100-8ea9-0a7dafecd92f.png) | ![image](https://user-images.githubusercontent.com/77069011/210884585-39399982-087a-487b-8136-3a52f9520a38.png) |

- [ ] It would be great if you improve the alignment of the elements inside each article and also use a smaller font size! 🤓 🛠️ 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/210885058-e7de67f9-78c9-4f91-bb97-c540fb92a3b6.png) | ![image](https://user-images.githubusercontent.com/77069011/210884966-b7b44408-c921-4495-a9ce-d7135631b579.png) |

- [ ] As for the desktop version, it would be great if you increase the height of each article as well as the height of the entire section! 🤓 🛠️ 

- [ ] **[OPTIONAL]:** Kudos if you implement the hover effect feature on each article! 🚀

2023-01-05 21:55 UTC, anagudelogu commented on assets/style/about.css
> +}
- [ ] **[OPTIONAL]:** I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️ 

From [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
![image](https://user-images.githubusercontent.com/77069011/200000947-9e58c4d8-fed4-45f8-a822-7828c6e713f7.png)


In this case, you could do this with flex:

```CSS
.flex {
  display: flex;
}
``` 

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2023-01-05 21:55 UTC, anagudelogu commented on assets/script/script.js
> +}
- [ ] **[OPTIONAL]:** Excellent job displaying your speakers section dynamically! 🚀 Just one suggestion: It would be nice to use `forEach` instead of a normal `for` in this case:

```suggestion
speakers.forEach((speaker)=>{
  const speakerCard = document.createElement('div');
  speakerCard.classList.add('speaker');

  const picture = document.createElement('img');
  picture.classList.add('speaker-image');
  picture.src = speaker.picture;
  picture.alt = `${speaker.name} image`;

  const profile = document.createElement('div');
  profile.classList.add('profile');

  const name = document.createElement('h4');
  name.classList.add('name');
  name.textContent = speaker.name;
  const profession = document.createElement('p');
  profession.classList.add('profession');
  profession.textContent = speaker.profession;
  const decoration = document.createElement('img');
  decoration.src = speaker.decoration;
  decoration.alt = 'profession decoration';
  const details = document.createElement('p');
  details.textContent = speaker.details;

  profile.append(name, profession, decoration, details);
  speakerCard.append(picture, profile);
  speakersContainer.append(speaker);
}
```

It improves a bit the readability, and if you're curious, it is possible to improve it, even more, using object destructuring. But don't worry too much about this, you're going to learn it in the next module! Keep up the great work! 🚀 

```suggestion
speakers.forEach(({name, profession, details, picture, decoration})=>{
  const speakerCard = document.createElement('div');
  speakerCard.classList.add('speaker');

  const picture = document.createElement('img');
  picture.classList.add('speaker-image');
  picture.src = picture;
  picture.alt = `${name} image`;

  const profile = document.createElement('div');
  profile.classList.add('profile');

  const name = document.createElement('h4');
  name.classList.add('name');
  name.textContent = name;
  const profession = document.createElement('p');
  profession.classList.add('profession');
  profession.textContent = profession;
  const decoration = document.createElement('img');
  decoration.src = decoration;
  decoration.alt = 'profession decoration';
  const details = document.createElement('p');
  details.textContent = details;

  profile.append(name, profession, decoration, details);
  speakerCard.append(picture, profile);
  speakersContainer.append(speaker);
}
```

2023-01-06 00:58 UTC, Owusu-Desmond approved these changes
Hi @biruk-bereka , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 01:01 UTC, merged